import type { Corpus } from "@/lib/schema";

const trail = {
  review_status: "published" as const,
  created_at: "2026-09-01",
  updated_at: "2026-09-01",
};

/** Corpus mínimo válido: 2 pessoas, 1 organização, 1 evento, 1 relação D, 1 relação A. */
export function minimalCorpus(): Corpus {
  return {
    built_at: "2026-09-01T00:00:00.000Z",
    people: [
      {
        id: "pessoa-a",
        kind: "person",
        name: "Pessoa A",
        aliases: [],
        category: "banker",
        role: "Controlador",
        positions: [],
        summary: "Resumo neutro.",
        why_in_novelo: "Frase factual.",
        cited_position: [{ kind: "not_located", summary: "Não localizada.", source_ids: [] }],
        open_questions: [],
        tags: [],
        source_ids: ["src-oficial"],
        ...trail,
      },
      {
        id: "pessoa-b",
        kind: "person",
        name: "Pessoa B",
        aliases: [],
        category: "politician",
        role: "Senador",
        positions: [],
        summary: "Resumo neutro.",
        why_in_novelo: "Frase factual.",
        cited_position: [],
        open_questions: [],
        tags: [],
        source_ids: [],
        ...trail,
      },
    ],
    organizations: [
      {
        id: "org-x",
        kind: "organization",
        name: "Org X",
        aliases: [],
        org_type: "financial_institution",
        summary: "Resumo.",
        why_in_novelo: "Frase.",
        cited_position: [],
        open_questions: [],
        tags: [],
        source_ids: [],
        ...trail,
      },
    ],
    events: [
      {
        id: "evt-2025-11-18-teste",
        kind: "event",
        title: "Evento de teste",
        event_type: "investigation_step",
        date: "2025-11-18",
        date_precision: "day",
        participant_ids: ["pessoa-a", "org-x"],
        description: "Descrição.",
        evidence_class: "D",
        status: "verified",
        evidence_ids: ["ev-d"],
        source_ids: ["src-oficial"],
        document_ids: ["doc-1"],
        public_act_ids: [],
        cited_position: [],
        tags: [],
        ...trail,
      },
    ],
    relationships: [
      {
        id: "rel-pessoa-a-org-x-corporate",
        kind: "relationship",
        from_id: "pessoa-a",
        to_id: "org-x",
        relationship_type: "corporate",
        directed: false,
        label: "controlador",
        description: "Por quê.",
        evidence_class: "D",
        confidence: 0.9,
        status: "verified",
        event_ids: ["evt-2025-11-18-teste"],
        evidence_ids: ["ev-d"],
        source_ids: [],
        document_ids: [],
        transaction_ids: [],
        cited_position: [],
        tags: [],
        ...trail,
      },
      {
        id: "rel-pessoa-a-pessoa-b-allegation",
        kind: "relationship",
        from_id: "pessoa-a",
        to_id: "pessoa-b",
        relationship_type: "investigative_allegation",
        directed: false,
        label: "segundo a PF",
        start_date: "2026-05-07",
        description: "Alegação.",
        evidence_class: "A",
        confidence: 0.5,
        status: "unverified",
        event_ids: [],
        evidence_ids: ["ev-a"],
        source_ids: ["src-imprensa"],
        document_ids: [],
        transaction_ids: [],
        cited_position: [
          {
            by_id: "pessoa-b",
            kind: "denial",
            summary: "Pessoa B negou a relação.",
            source_ids: ["src-imprensa"],
          },
        ],
        tags: [],
        ...trail,
      },
    ],
    claims: [],
    sources: [
      {
        id: "src-oficial",
        kind: "source",
        title: "Nota oficial",
        publisher: "STF",
        retrieved_at: "2026-09-01",
        url: "https://noticias.stf.jus.br/x",
        source_type: "official_court",
        language: "pt-BR",
        verification: {
          checked_at: "2026-09-01",
          checked_by: "teste",
          url_reachable: true,
          content_matches_summary: true,
        },
        ...trail,
      },
      {
        id: "src-imprensa",
        kind: "source",
        title: "Reportagem",
        publisher: "Jornal",
        retrieved_at: "2026-09-01",
        url: "https://jornal.example/x",
        source_type: "press",
        language: "pt-BR",
        ...trail,
      },
    ],
    documents: [
      {
        id: "doc-1",
        kind: "document",
        title: "Decisão",
        doc_type: "judicial_decision",
        date: "2025-11-18",
        source_ids: ["src-oficial"],
        summary: "Resumo.",
        is_official: true,
        related_entity_ids: [],
        tags: [],
        ...trail,
      },
    ],
    public_acts: [],
    transactions: [],
    evidence: [
      {
        id: "ev-d",
        kind: "evidence",
        classification: "D",
        proposition: "Proposição documentada.",
        document_ids: ["doc-1"],
        source_ids: ["src-oficial"],
        ...trail,
      },
      {
        id: "ev-a",
        kind: "evidence",
        classification: "A",
        proposition: "Segundo a PF, algo.",
        document_ids: [],
        source_ids: ["src-imprensa"],
        attributed_to: "Polícia Federal",
        ...trail,
      },
    ],
    sequences: [],
    revisions: [],
  };
}
